### ISSUE TITLE
[Bug]: Opened-file-aware suggestions doesn't work

### ISSUE THREAD

**Issue by MaksimBezdrobnoi** [intitni/CopilotForXcode#193]
### Before Reporting

- [X] I have checked FAQ, and there is no solution to my issue
- [X] I have searched the existing issues, and there is no existing issue for my issue

### What happened?

I opened two files(one with an enum, a second where I want to write the extension on this enum) and Copilot suggest the incorrect switch
<img width="1649" alt="image" src="https://user-images.githubusercontent.com/85101110/236144605-0a7b6376-2bb0-46c2-94d4-c1385c1fa911.png">

### How to reproduce the bug.

1. Write an enum
2. Write an extension on this enum in a separate file

### macOS version

13.3.1

### Xcode version

14.3

### Copilot for Xcode version

14.1

**Comment by intitni** [comment]
Have you ever tried switching to the left editor before generating a suggestion? The app now dependends on  the focused element change notification as a hint to send an open file notification to GitHub Copilot. However, if you are opening files from the side bar but never clicking into the editor, it may miss those opened files.

This is a limitation of the app and I am still looking for a workaround.

**Comment by MaksimBezdrobnoi** [comment]
https://user-images.githubusercontent.com/85101110/236160420-68e544cd-a5fc-4db3-93fe-c988a9064f90.mov

**Comment by intitni** [comment]
What happens if you restart the helper app and to the same thing again? There is a chance that a file will be registered to another workspace if the app can't get its project path in some situations. You can quit the helper app from the context menu of the widget and restart it by calling any command from the Copilot menu.

**Comment by intitni** [comment]
As far as I can tell. Even in VSCode, GitHub Copilot can't generate the correct suggestion for this code when it's mixed with other code. And it works in Swift playground..

<img width="1205" alt="Screenshot 2023-05-04 at 22 38 18" src="https://user-images.githubusercontent.com/793147/236241314-bcadd0e3-5fd4-4b05-b77f-b5143cc26db4.png">

<img width="1035" alt="Screenshot 2023-05-04 at 22 41 51 1" src="https://user-images.githubusercontent.com/793147/236242350-875f8b3d-906c-4ce5-9c47-faaa8a9ff80d.png">

**Comment by kdubroff** [comment]
I'm seeing the same behavior where Copilot is recommending I use subroutines that don't exist unless I explicitly ask for that subroutine to be used in a comment. In one instance, I'm asking for a recommendation in the left pane. The left pane is calling a singleton that I have opened in the right pane. Copilot suggests I use subroutines that don't exist in the singleton rather than using existing ones.
