### ISSUE TITLE
[Bug]: Clicking "Accept" doesn't apply the code 

### ISSUE THREAD

**Issue by unniverzal** [intitni/CopilotForXcode#311]
### Before Reporting

- [X] I have checked FAQ, and there is no solution to my issue
- [X] I have searched the existing issues, and there is no existing issue for my issue

### What happened?

When clicking "Accept" nothing happens. 
Restarting the Xcode or Mac doesn't resolve the issue. 

### How to reproduce the bug.

It just happens!

### Relevant log output

```shell
None
```

### macOS version

13.3.1

### Xcode version

Version 14.3.1 (14E300c)

### Copilot for Xcode version

0.20.1

### Node version

v18.16.1

**Comment by intitni** [comment]
1. Make sure you have setup the Xcode source editor extension, as described in README.md.
2. Make sure the `Copilot` menu is available under Xcode menu - Editor. If it's not there, restart Xcode.
3. If it's not fixed, you can try turning on Always accept suggestions with Accessibility API in advanced settings if you are sure that the app is correctly setup.

**Comment by intitni** [comment]
@mavzerbay It's weird that the 3rd step isn't working for you. Since the whole extension works more like a hack, I can guarantee that what works for me works for others. I can't fix it alone.

I would suggest:
1. Make sure there is only one version of Copilot for Xcode.app exists on your Mac.
2. Make sure that you have opened the app once and restarted Xcode after each update.
3. Leave more information, for example, is the Copilot menu available? Can you accept suggestion from the menu? Are you using a prebuilt version of the app or are your building the app yourself? 
4. Install the previous versions and report the last version that works for you.
5. Build and run the ExtensionService target, add a break point at `PseudoCommandHandler.acceptSuggestion` and click the accept button.

**Comment by chrishendersonc4** [comment]
I had this problem until I deleted the "Copilot for Xcode.app" from my Downloads folder and restarted Xcode. I had previously copied it to /Applications, but I should have moved it instead. The giveaway was seeing two octopus tentacle icons (the icon for this app, Copilot for Xcode) in my menu bar.

**Comment by ben-p-commits** [comment]
For me, quitting "Copilot for Xcode.app" fixed this issue.

**Comment by Dark-Existed** [comment]
I hava the same problem, this happen to me when I open mulit Xcode project. When I turning on Always accept suggestions with Accessibility API in advanced settings, click accept will works, but the other projacts whill appear to foregroud. Even the keybinding is setted, the keybinding is not working. So may the problem about solving the window focus. 

Xcode version 15.0.1

**Comment by intitni** [comment]
@Dark-Existed, if the keybinding is not working either, the Copilot menu in Xcode is probably grayed out. It's an issue with Xcode and can only be cured by restarting Xcode. It usually happens after you have updated Copilot for Xcode which may confuse Xcode. 

Always accept suggestions with Accessibility API is a fallback solution that insert the suggestion to the editor with Accessibility API, I guess it has a side effect the bring everything of the app to foreground. I am considering replacing it with a pasteboard base solution, no ETA yet.

**Comment by Dark-Existed** [comment]
@intitni thx, after restarting Xcode, it works for me.

**Comment by intitni** [comment]
@mehmetbaykar Please try #438. Post a screenshot of the Copilot menu to #438 if the issue persists.
