### ISSUE TITLE
[Bug]: Unable to accept suggestions

### ISSUE THREAD

**Issue by bc1213** [intitni/CopilotForXcode#363]
### Before Reporting

- [X] I have checked FAQ, and there is no solution to my issue
- [X] I have searched the existing issues, and there is no existing issue for my issue

### What happened?

After signing into co-pilot for xcode,

In my xcode suggestions are coming, but when i try to accept suggestion it is giving  this error

The command accept suggesion failed

![Screenshot 2023-09-22 at 10 24 31 AM](https://github.com/intitni/CopilotForXcode/assets/30365864/532d8c49-bdd1-4f3b-8072-c234cf8799f7)

### How to reproduce the bug.

Happening everytime

Tried with two system

Core i7 and Mac M1 also

### macOS version

13.4.1 (c) 

### Xcode version

14.3.1 and 15 also

### Copilot for Xcode version

0.23.2 (241)

### Node version

v20.2.0

**Comment by intitni** [comment]
The only case the accept suggestion command can fail is when it can't talk to the extension service. But if it can't talk to the extension service, it will not be able to start the extension service when Xcode launches. It's weird. 

Please let me know:
1. Did you put the Copilot for Xcode.app in the Applications folder?
2. Did you start the extension service app manually?
3. Can you see the extension service version from the Copilot for Xcode.app
4. Do you have multiple version of Copilot for Xcode.app on your Mac?
5. Does the "The command failed" warning show up immediately after you accept the suggestion?
6. What happens when you click Accept Suggestion from Editor > Copilot > Accept Suggestion?

**Comment by bc1213** [comment]
@intitni :
Sorry the issue was due to Not moved to Application folder

After moving its working now.
Thanks

**Comment by intitni** [comment]
Glad to hear that. I will add a notice to the README later.
