### ISSUE TITLE
[Bug]: Custom (GPT-4) model not working with chat

### ISSUE THREAD

**Issue by ansh** [intitni/CopilotForXcode#372]
### Before Reporting

- [X] I have checked FAQ, and there is no solution to my issue
- [X] I have searched the existing issues, and there is no existing issue for my issue

### What happened?

I wanted to use GPT-4 with Chat and since I bought the premium version of Copilot for XCode, and have the GPT-4 API, I thought this would be possible very easily. 

Unfortunately, it seems like the Chat keeps using `gpt-3.5-turbo` even if I change the model to GPT-4.

### How to reproduce the bug.

1. I created a new model called "GPT-4" as shown below
![CleanShot 2023-10-11 at 22 14 11@2x](https://github.com/intitni/CopilotForXcode/assets/8207733/28c1ea83-df74-45ef-a6b0-fab7c5828280)
2. I set the model for Chat to GPT-4
![CleanShot 2023-10-11 at 22 14 01@2x](https://github.com/intitni/CopilotForXcode/assets/8207733/b5fd2a77-d7da-40c5-8230-91d578613a0f)
3. I asked the chat model what it is and it says `gpt-3.5-turbo`
![CleanShot 2023-10-11 at 22 14 03@2x](https://github.com/intitni/CopilotForXcode/assets/8207733/dded18bb-76bb-4806-9310-82cbec1db98f)
4. If I ask ChatGPT with GPT-4 on what model it is, it always says GPT-4.

### macOS version

14.0 Sonoma

### Xcode version

15.0

### Copilot for Xcode version

0.25.0

### Node version

v18

**Comment by intitni** [comment]
This is not how LLM works. GPT-4 doesn't know anything that happened after January 2022, so technically, it doesn't even know about GPT-4.

However, if you are using the ChatGPT web app, OpenAI may have tweaked its system prompt to include something like "you are using the model GPT-4", so that it can reply with the correct answer.

If you want to confirm that it's using the correct model, you can:

- MITM the requests and check the model name in the request body.
- Check the usage on openai.com by hovering your mouse over the bar chart (please note that the chart is not real-time).
