### ISSUE TITLE
[Enhancement]: Can integrate locally deployed LLM

### ISSUE THREAD

**Issue by gixiphy** [intitni/CopilotForXcode#382]
### Before Requesting

- [X] I have searched the existing issues, and there is no existing issue for my feature request

### What feature do you want?

Can integrate locally deployed LLM
Like something like this
https://github.com/danielgross/localpilot

**Comment by intitni** [comment]
After implementing the project scope and some other project scope related feature (in 1 or 2 more versions), I will be experimenting to allow third party extensions to provide suggestion and chat features. 

If it goes well, I think this can be implemented as an extension. If it doesn't go well, I will consider allowing users to use a completion model as the backend of the suggestion feature.

But running an LLM inside the app will be out of scope.

I just checked the link you posted, it looks like it's using the GitHub Copilot proxy to redirect it to use other LLMs. Copilot for Xcode supports GitHub Copilot proxy (in the GitHub Copilot settings, not realy tested), and you can give it a try, let me know if it works or not.

**Comment by mirko-milovanovic-vidiemme** [comment]
Hi, regarding this issue, i've wanted to use a local LLM through [Ollama](https://ollama.ai/) and the [litellm OpenAPI proxy](https://github.com/BerriAI/litellm#openai-proxy---docs) (which takes the Ollama api and converts it to a compatible OpenAPI spec) for the Chat and Promt to Code features of the plugin

I've sort of managed to get it working but the Chat feature doesn't work quite right because the answer tokens are streamed from the local litellm proxy to the CopilotForXcode chat box as single messages, making it unreadable and unusable

I don't have any clue if it's a proxy problem, ollama problem or the way the plugin makes requests to the proxy (because using the OpenAPI servers it works as expected)

I've wanted to know it it was possible to make it work or if it was a interesting feature to include/implement

Here's and example vid demonstrating the issue:

https://github.com/intitni/CopilotForXcode/assets/116636082/043361b4-6e29-458c-9edb-8562447e31e0

<img width="1012" alt="Screenshot 2023-11-17 alle 10 48 26" src="https://github.com/intitni/CopilotForXcode/assets/116636082/ff422e6b-28b3-429c-8c20-a194bafe7dea">

**Comment by intitni** [comment]
I think it happens because the service is returning each token with a different ID. I will see what I can do with it in the hot fix releasing later today.

**Comment by mirko-milovanovic-vidiemme** [comment]
Thanks for the quick response! I've also discovered that using the Prompt to Code feature the messages do actually behave as expected which is something to consider

https://github.com/intitni/CopilotForXcode/assets/116636082/637b23fa-7961-4742-8cbf-c453a43754c0

**Comment by mirko-milovanovic-vidiemme** [comment]
This is what i managed to log for the promt to code request that seemingly seems to work (tho it's pretty ugly and kinda unreadable) 
[debug.txt](https://github.com/intitni/CopilotForXcode/files/13392096/debug.txt)

**Comment by intitni** [comment]
@mirko-milovanovic-vidiemme please give 0.27.1 a try

**Comment by mirko-milovanovic-vidiemme** [comment]
Yup, it seems to be working as expected now! Thanks for the quick fix

**Comment by intitni** [comment]
Now that [CopilotForXcodeKit](https://github.com/intitni/CopilotForXcodeKit), as mentioned before, I will make an extension that provides suggestion service via the local models.

**Comment by intitni** [comment]
Suggestion feature with locally running model is [released](https://github.com/intitni/CopilotForXcode/discussions/443)
