### ISSUE TITLE
[Help Wanted]: Not Getting Suggestions in JUCE C++ projects

### ISSUE THREAD

**Issue by discohead** [intitni/CopilotForXcode#404]
### Before Reporting

- [X] I have checked FAQ, and there is no solution to my issue
- [X] I have searched the existing issues, and there is no existing issue for my issue

### Describe your issue

Hello, I have an active Plus license and the plugin is working well for me in Swift projects and even in [openFrameworks](https://openframeworks.cc) C++ projects but for some reason I get no suggestions whatsoever in [JUCE](https://juce.com) C++ projects. Chat works in those projects but not suggestions. I'm using Github Copilot and like I said, it works fine in Swift and even C++ Xcode projects generated by the openFrameworks [Project Generator](https://openframeworks.cc/learning/01_basics/create_a_new_project/). But I get no suggestions in C++ Xcode projects generated by the [JUCE Projucer](https://docs.juce.com/master/tutorial_new_projucer_project.html). Any ideas what the issue might be?

**Comment by intitni** [comment]
Do you have an example project that I can try?

**Comment by discohead** [comment]
Sure, this is the default project from JUCE's Projucer: https://github.com/discohead/juceXcodePilotExample

It's not going compile as its linked to my local JUCE SDK path, but maybe doesn't matter for this purpose.

**Comment by intitni** [comment]
It looks like the project is using `\r\n` as line endings, which is not handled in the app. Supporting it will take some time since I am calling `.split(separator: "\n")` everywhere in the code. 

In the meantime, if the line endings don't matter, you can turn this toggle on in Xcode settings - Text Editing - Editing to convert them into `\n`.

<img width="464" alt="Screenshot 2023-12-19 at 14 59 08" src="https://github.com/intitni/CopilotForXcode/assets/793147/f466813b-aede-4bf1-b88a-ed6e304dc334">

**Comment by intitni** [comment]
But the toggle is not working for me..

**Comment by discohead** [comment]
I see. Unfortunately, same here, that toggle doesn't seem to have any effect on the issue.

**Comment by discohead** [comment]
Just confirming that it's definitely the line endings. I wrote a bash script to convert them and now I'm getting suggestions.

**Comment by intitni** [comment]
Released in 0.29.0.
