### ISSUE TITLE
[Bug]: Suggestions are not working

### ISSUE THREAD

**Issue by jbruckne** [intitni/CopilotForXcode#426]
### Before Reporting

- [X] I have checked FAQ, and there is no solution to my issue
- [X] I have searched the existing issues, and there is no existing issue for my issue

### What happened?

No suggestions are appearing while using the tool. If I try to force suggestions with the key binding, nothing happens. I do not see the widget animate. Also, if I manually open the widget, it simply shows "Empty". No errors seen during any of this.

I tried complete uninstall and reinstall via homebrew --cask.

One thing I noticed: Xcode Inspector Debug > XCode 7080 > "Is Active: false". Not sure what this means or how to make it active. Happy to share some logs, if you can tell me where they are stored.

Extension Service Version: 0.30.0
Accessibility Permission: Granted

Copilot.Vim version: 1.12.1
Language Server Version: 1.94.0
Status: OK

### How to reproduce the bug.

It just happens!

### macOS version

14.2

### Xcode version

15.2

### Copilot for Xcode version

0.30.0

### Node version

18.19.0

**Comment by intitni** [comment]
You can find the logs in realtime in Console.app. The status will be active when Xcode is the frontmost application. The chat panel will be empty until you open a chat panel by clicking the + button.

Please check that, When the text cursor is inside an Xcode editor, 
- the widget can attach to the editor, instead of the Xcode window.
- from the Xcode Inspector Debug menu, the value of Active Source Editor is Source Editor.

If they are not, try switching between apps and editors. If they are still not, try the version in #415. You can find the latest build in the very bottom of the issue.

**Comment by Romaaan3** [comment]
No suggestions for me as well
Version 0.30.3
Xcode 15.2
Build version 15C500b

**Comment by intitni** [comment]
@Romaaan3 Please 
- Check that if the [FAQ](https://github.com/intitni/CopilotForXcode/wiki/Frequently-Asked-Questions#q-host-app-shows-server-unavailable-please-make-sure-you-have-installed-node-or-github-copilot-not-working) can solve your problem.
- show me your settings. Including the GitHub Copilot settings, suggestion feature settings and the general settings.
- Turn on verbose log in the GitHub Copilot settings, open Console.app and click start streaming, set the filter to `category:GitHubCopilot`. Then type something in Xcode to trigger realtime suggestion and show me the logs.
