### ISSUE TITLE
[Enhancement]: Add Google's Gemini support

### ISSUE THREAD

**Issue by Kyle-Ye** [intitni/CopilotForXcode#458]
### Before Requesting

- [X] I have searched the existing issues, and there is no existing issue for my feature request

### What feature do you want?

Do we have plan to support Gemini here?

Gemini currently has a much friendly free plan for dev now.

And many other AI based app(eg. OpenCat) has provided multi services support here.

After updating to the latest version and unlocking the plus feature, I still did not find a entry to add other non-OpenAI chat service.

eg. 
![Screenshot of OpenCat App](https://github.com/intitni/CopilotForXcode/assets/43724855/6e894bbd-8f82-4c04-bfc3-3563bab31244)

**Comment by intitni** [comment]
It's already there. Since nobody knows if Google will someday drop the name Gemini, I used "Google Generative AI". 

<img width="826" alt="Screenshot 2024-03-14 at 00 35 32" src="https://github.com/intitni/CopilotForXcode/assets/793147/9d228c7b-7e2c-4599-82bd-a801603c7845">

To add other services, you need to add a chat model by clicking this button.

<img width="1012" alt="Screenshot 2024-03-14 at 00 38 17" src="https://github.com/intitni/CopilotForXcode/assets/793147/c8f51726-4e21-41eb-9544-651261e7445a">

**Comment by Kyle-Ye** [comment]
Thanks for the clear explanation.

**Comment by Kyle-Ye** [comment]
Got the root issue here. I'm still using 0.28.3 which does have the plus button here.😂

The auto update just failed somehow last time.
