### ISSUE TITLE
[Help Wanted]: FetchError when loading Copilot suggestions with proxy

### ISSUE THREAD

**Issue by dmitryd20** [intitni/CopilotForXcode#510]
### Before Reporting

- [X] I have checked FAQ, and there is no solution to my issue
- [X] I have searched the existing issues, and there is no existing issue for my issue

### Describe your issue

I have been using Copilot for Xcode with proxy for several months and it was working perfectly. At some moment suggestions stopped working. Details:

1. Application shows "Status: OK" when using proxy.
<img width="668" alt="Снимок экрана 2024-05-14 в 15 02 33" src="https://github.com/intitni/CopilotForXcode/assets/28758703/aab585f0-8507-4121-8946-07fbd09eff0d">

2. When triggering suggestions loading from Xcode editor, I see the following two errors from CopilotForXcodeExtensionService:
- Request Error: (FetchError) Hostname/IP does not match certificate's altnames: Host: copilot-proxy.githubusercontent.com. is not in the cert's altnames: DNS:*.gist.githubusercontent.com, DNS:gist.githubusercontent.com
- Error on ghost text request: (FetchError) Hostname/IP does not match certificate's altnames: Host: copilot-proxy.githubusercontent.com. is not in the cert's altnames: DNS:*.gist.githubusercontent.com, DNS:gist.githubusercontent.com

3. All of my iOS teammates have the same error.
4. My Android teammates use the same proxy with Jetbrains IDE Copilot plugin and it still works without any problems.

What have I tried:
- Using no proxy / using VPN connection
- Reinstalling Copilot for Xcode with clearing all stored preferences
- trying different versions of Copilot for Xcode

**Comment by intitni** [comment]
It looks like the language server was trying to access [https://copilot-proxy.githubusercontent.com](https://copilot-proxy.githubusercontent.com) but the certificate was incorrect. What happens if you access it directly in Safari?

How did you setup the proxy?

If you are using self signed certificate, please use the workaround if [this issue](https://github.com/intitni/CopilotForXcode/issues/455).

If you would like to try the latest version of the language server, you can download it from [copilot.vim](https://github.com/github/copilot.vim) and extract the dist folder into ~/Library/Application\ Support/com.intii.CopilotForXcode/GitHub\ Copilot/executable/copilot

**Comment by dmitryd20** [comment]
Tried the latest Language Server version from Copilot.vim v1.31. And it works without any errors/warnings.

So, the reason was inside the Language Server. Thanks for help!
