### ISSUE TITLE
[Bug]: Codestral fim

### ISSUE THREAD

**Issue by pwnified** [intitni/CopilotForXcode#531]
### Before Reporting

- [X] I have checked FAQ, and there is no solution to my issue
- [X] I have searched the existing issues, and there is no existing issue for my issue

### What happened?

Any reason why Codestral Fim wont work? Seems like a 404 error, but I know that endpoint works. The Chat endpoint works.

### How to reproduce the bug.

https://codestral.mistral.ai/v1/fim/completions
Model Name: codestral-latest

![Screenshot 2024-06-02 at 2 42 26 PM](https://github.com/intitni/CopilotForXcode/assets/1249591/157fd8ef-50ee-44eb-a569-a572a83b7587)

![Screenshot 2024-06-02 at 2 45 35 PM](https://github.com/intitni/CopilotForXcode/assets/1249591/eacc3a22-b7f2-432e-bea6-61723667942f)

![Screenshot 2024-06-02 at 2 47 30 PM](https://github.com/intitni/CopilotForXcode/assets/1249591/c9fc105a-0568-4aa1-ae96-fa7f9e831273)

### macOS version

14.5 (23F79)

### Xcode version

Version 15.4 (15F31d)

### Copilot for Xcode version

Version 0.33.2 (385)

**Comment by intitni** [comment]
Hello, it's not a chat completions endpoint but a FIM (Fill in the middle) endpoint that works only for code completions. It's not supported yet since it's the first time I have heard of it. 

Please submit a feature request to [CustomSuggestionServiceForCopilotForXcode](https://github.com/intitni/CustomSuggestionServiceForCopilotForXcode). I will work on it later.

**Comment by intitni** [comment]
Released in https://github.com/intitni/CustomSuggestionServiceForCopilotForXcode/releases/tag/0.4.0
