### ISSUE TITLE
[Enhancement]: Chat Model per Tab

### ISSUE THREAD

**Issue by cliffordh** [intitni/CopilotForXcode#537]
### Before Requesting

- [X] I have searched the existing issues, and there is no existing issue for my feature request

### What feature do you want?

I would like to specify the chat model to use when creating a new tab in the chat panel. This would allow me to have specific tabs for specific types of requests that are tuned for a given model, e.g., translation, writing documentation, coding, etc. and maintain the context for each type of interaction separately.

**Comment by intitni** [comment]
You can already do that by right-clicking the title or each tab to open a context menu. You can change the chat model, temperature and scopes for each tab.

When you use multiple chat tabs, you may find a bug that you can only scroll up in the first chat tab. It will be fixed in the coming release this weekend.

**Comment by cliffordh** [comment]
Thank you!
