### ISSUE TITLE
Xcode autocomplete broken

### ISSUE THREAD

**Issue by mfbx9da4** [intitni/CopilotForXcode#80]
First of all, thanks very much for putting this together! It's been very helpful to me and I use it daily 🙌 .

I'm finding after installing this plugin, Xcode's auto complete breaks and I can no longer use it. The autocomplete appears for a second and then disappears 

https://user-images.githubusercontent.com/1690659/227732142-1def2908-8791-497f-afcd-4c8bbd46e0c1.mov

**Comment by mrk-han** [comment]
If you manually toggle autocomplete with esc or control + space does the autocomplete still go away?

**Comment by Shreyas-SAS** [comment]
@mfbx9da4 Ok. I will try to contribute to this issue. Please instruct me if there are any particular triggers and if this happens after every special character or just the '.'

**Comment by intitni** [comment]
> @mfbx9da4 Ok. I will try to contribute to this issue. Please instruct me if there are any particular triggers and if this happens after every special character or just the '.'

My guess is that it's caused by the limitation 4 mentioned in README.md, and for some reasons, the caching is not working for mfbx9da4. Which also explains the 1 second delay. The cache is in the type `Filespace`. One quick fix is to give them a default value, so we never need to trigger real-time suggestion via Apple Script any more. Deciding the default value of `uti` may seem hard, but I don't remember using it anywhere. Another type you can look out for, if you would like to contribute,  is the `PseudoCommandHandler` where the cache is read and the real-time suggestion is triggered.

**Comment by andersnicolai** [comment]
Hey, great extension, if I click accept nothing happens, but the reject button works...

**Comment by intitni** [comment]
> Hey, great extension, if I click accept nothing happens, but the reject button works...

Check #70

**Comment by intitni** [comment]
Please try release 0.10.0 to see if it's fixed.
