### ISSUE TITLE
Prompt doesn't show up

### ISSUE THREAD

**Issue by rryan2** [intitni/CopilotForXcode#84]
I followed the instructions and turned on the accessibility in privacy and security. The circular button shows up in my Xcode, but there's no prompt on the right of the button.
[https://ibb.co/c3yh8hP](url)

**Comment by rryan2** [comment]
<img width="481" alt="123" src="https://user-images.githubusercontent.com/25201880/227808067-2ed7a1c8-77f0-4792-85ab-48c21207eab6.png">

**Comment by intitni** [comment]
Please make sure the GitHub Copilot status is OK. If it's not, it's likely that your GitHub Copilot subscription is not valid.

**Comment by rryan2** [comment]
<img width="241" alt="image" src="https://user-images.githubusercontent.com/25201880/228759099-48cb8b92-8494-463a-9fd8-c6a8f44b85b0.png">
It looks good here

**Comment by intitni** [comment]
- Does the command `Get Suggestions` work for you?
- Did you turn on `Real-time suggestions` in the host app?
- If so, do you see any animation around the circular button when you stop typing? Don't press enter or arrow keys because they will cancel real-time suggestions.
- If not, open Console.app and filter logs from `CopilotForXcodeExtensionService`, do you see any log with content `Prefetch suggestions.` when you stop typing?

**Comment by gmoraleda** [comment]
Experiencing the same issue
